# backend/blog/serializers.py

from rest_framework import serializers
from .models import BlogPost

class BlogPostSerializer(serializers.ModelSerializer):
    # CRITICAL FIX: Use SerializerMethodField to get the absolute URL from the model property
    cover_image_url = serializers.SerializerMethodField() 

    class Meta:
        model = BlogPost
        # Change fields to include the new property and exclude the original FileField if necessary
        fields = ('id', 'title', 'slug', 'content', 'cover_image_url', 'tags', 'is_published', 'created_at', 'read_time')

    def get_cover_image_url(self, obj):
        # Return the URL generated by the @property we created in the model
        return obj.cover_image_url