# backend/blog/serializers.py

from rest_framework import serializers
from .models import BlogPost

class BlogPostSerializer(serializers.ModelSerializer):
    # CRITICAL FIX: Use the new property for absolute URL
    cover_image = serializers.SerializerMethodField() 

    class Meta:
        model = BlogPost
        fields = '__all__'

    def get_cover_image(self, obj):
        # Return the URL generated by the @property we created in the model
        return obj.cover_image_url