# Generated by Django 6.0 on 2025-12-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='vault/')),
                ('category', models.CharField(choices=[('RESUME', 'Resume & CV'), ('DOCS', 'Personal Documents'), ('BACKUP', 'Project Backups'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(blank=True, help_text='Size in KB/MB', max_length=20)),
            ],
        ),
    ]
