# Generated by Django 6.0 on 2025-12-06 10:11

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefile',
            name='category',
            field=models.CharField(choices=[('RESUME', 'Resume & CV'), ('DOCS', 'Personal Documents'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='privatefile',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='vault/'),
        ),
        migrations.AlterField(
            model_name='privatefile',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
