# Generated by Django 6.0 on 2025-12-06 01:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(help_text='Browser/OS Details')),
                ('device_type', models.CharField(default='Desktop', max_length=20)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='The URL they visited', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('referrer', models.CharField(blank=True, help_text='Where did they come from?', max_length=500, null=True)),
                ('status_code', models.IntegerField(default=200)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.visitor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
