# Generated by Django 6.0 on 2025-12-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='ip_address',
            new_name='remote_ip',
        ),
        migrations.AddField(
            model_name='visitor',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_visit',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
