# Generated by Django 6.0 on 2025-12-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_ip_address_visitor_remote_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visits',
            field=models.IntegerField(default=1),
        ),
    ]
