# Generated by Django 6.0 on 2025-12-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Paste the absolute Cloudinary/Image URL here.', max_length=500, null=True),
        ),
    ]
