# Generated by Django 6.0 on 2025-12-06 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issuer', models.CharField(max_length=100)),
                ('date_issued', models.DateField()),
                ('credential_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certs/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="URL friendly name (e.g. 'ecommerce-api')", unique=True)),
                ('tagline', models.CharField(help_text='Short one-liner description', max_length=200)),
                ('description', models.TextField(help_text='Full details (Markdown supported)')),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('LANG', 'Languages (Python, JS)'), ('FRONT', 'Frontend (React, CSS)'), ('BACK', 'Backend (Django, Node)'), ('DEVOPS', 'DevOps (Docker, AWS)'), ('TOOL', 'Tools (Git, Linux)')], max_length=10)),
                ('proficiency', models.IntegerField(default=0, help_text='0 to 100')),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome class or similar', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on Home Page?')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_feature', models.BooleanField(default=False, help_text='Is this the main cover image?')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='projects', to='core.skill'),
        ),
    ]
