# Generated by Django 6.0 on 2025-12-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('date_range', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('EDU', 'Education'), ('WORK', 'Work / Internship'), ('ACHIEVEMENT', 'Achievement'), ('GOAL', 'Future Goal')], default='EDU', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Lowest number appears first')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
