# Generated by Django 6.0 on 2025-12-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='image',
        ),
        migrations.AddField(
            model_name='certificate',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste the absolute URL for the certificate image.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Paste the absolute URL for the main featured image.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_url',
            field=models.URLField(default='', help_text='Paste the absolute URL for this gallery image.', max_length=500),
            preserve_default=False,
        ),
    ]
