# Generated by Django 6.0 on 2025-12-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_certificate_image_remove_projectimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Automatically generated Open Graph image.', null=True, upload_to='project_og/'),
        ),
    ]
